### ISSUE TITLE
「ログインしてください」のモーダルが出た瞬間消える

### ISSUE THREAD

**Issue by cskd8** [traPtitech/Jomon#141]
ページ遷移すると出る
<img width="952" alt="スクリーンショット 2020-07-26 2 14 21" src="https://user-images.githubusercontent.com/57042565/88462358-c4095500-cee5-11ea-92f1-e08e45644dbb.png">
<img width="952" alt="スクリーンショット 2020-07-26 2 14 24" src="https://user-images.githubusercontent.com/57042565/88462362-c8ce0900-cee5-11ea-95f0-ab81be049b00.png">

**Comment by cskd8** [comment]
これはもう直ったとおもうのでクローズして大丈夫ですか？

**Comment by FujishigeTemma** [comment]
おっけー👍 
ref: #142
