### ISSUE TITLE
申請ができない

### ISSUE THREAD

**Issue by pois0** [traPtitech/Jomon#74]
## 事象
申請をPOSTしようとすると400が返ってくる。

### その1
https://github.com/traPtitech/Jomon/blob/55e4c1d343e344234e3708f704e51603d757fdec/client/src/views/NewApplicationPage.vue#L279
この`this.amount`が`string`になっているので`numer`に変換する必要がある。

### その2
https://github.com/traPtitech/Jomon/blob/55e4c1d343e344234e3708f704e51603d757fdec/client/src/views/NewApplicationPage.vue#L282
ここで`details`を`json`に変換できていないので`JSON.stringify`などをつかって`json`に落とす。

**Comment by sautzu** [comment]
指摘箇所を修正しましたが、いまだに新規作成ができません。(Bad requestが返ってくる)

**Comment by mdsboy** [comment]
クライアントから送信しているdetailsにpaid_atが含まれていないのが原因だと思います
