### ISSUE TITLE
samber/lo

### ISSUE THREAD

**Issue by H1rono** [traPtitech/Jomon#774]
https://github.com/traPtitech/Jomon/pull/771 でインストールした
他にも使えるところがあるかも？

**Comment by H1rono** [comment]
究極、`append`を撲滅できるよな

**Comment by H1rono** [comment]
https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/admin.go#L20-L23

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/model/tag_impl.go#L19-L22

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/model/user_impl.go#L54-L57

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/model/group_impl.go#L19-L22

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/model/group_impl.go#L84-L87

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/model/group_impl.go#L101-L104

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/model/group_impl.go#L130-L133

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/model/group_impl.go#L148-L151

**Comment by H1rono** [comment]
https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/transaction.go#L139-L147

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/transaction.go#L195-L203

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/transaction.go#L245-L253

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/transaction.go#L299-L307

↓バグに見える
https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L188-L195

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L197-L206

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L259-L265

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L298-L307

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L308-L316

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L317-L324

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L371-L381

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L393-L402

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L403-L411

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L412-L419

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L468-L474

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L501-L511

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L524-L532

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L533-L542

https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/request.go#L543-L550

**Comment by H1rono** [comment]
多すぎ...

**Comment by H1rono** [comment]
https://github.com/traPtitech/Jomon/blob/1db6bd33a09ac59e2af53df3024c9118814d37cf/router/request.go#L707-L717

ここ[`lo.Reduce`](https://github.com/samber/lo?tab=readme-ov-file#reduce)使える

**Comment by Hueter57** [comment]
`res`が一度`reses`を経由しているのは何か意味あるんですかね
https://github.com/traPtitech/Jomon/blob/6a1f7eb8de015e2bee30a6ef01da0a5f7583869f/router/transaction_test.go#L663-L693
ここだと`resOverview`を経由してます
https://github.com/traPtitech/Jomon/blob/6a1f7eb8de015e2bee30a6ef01da0a5f7583869f/router/transaction_test.go#L555

やってることが変わらないので一旦経由しているもの消して書いてます

**Comment by H1rono** [comment]
できますね、やっちゃってください
途中で`break`なり`return`なりが入っていない限りは`lo.Map`に置き換えてOK
可能であればPRでは置き換えなかった`for`文もできれば列挙して欲しいです

**Comment by H1rono** [comment]
closed by #789
